call testit all_cogs_blink
call testit crcbit_crcnib
call testit lock_test
call testit echo1
call testit echo2
call testit fibo
call testit fibo1
call testit fibo2
call testit fibo3
call testit MainLoader
call testit ml
call testit NTSC_256_x_192
call testit NTSC_256_x_192_interrupt
call testit p2pfth
call testit prefix
call testit printf
call testit programmer
call testit ROM_Booter_v32
call testit sin_cos_dacs
call testit single_step
call testit smartpin_pwm
call testit smartpin_serial_turnaround
call testit smartpin_usb_turnaround
call testit VGA_640_x_480_16bpp
call testit VGA_640_x_480_8bpp
call testit bas
call testit blink
call testit blinkit
call testit chess
call testit dry
call testit VGA_640_x_480_4bpp1
call testit testops
call testit test1
call testit tt
call testit xbyte
call testit xoro32
call testit xoroshiro128plus
call testit testjmploc
