typedef struct FatDirEntryS {
    char name[8];
    char ext[3];
    unsigned char attrib;
    unsigned char attrib1;
    unsigned char attrib2;
    unsigned short ctime;
    unsigned short cdate;
    unsigned short adate;
    unsigned short hcluster;
    unsigned short mtime;
    unsigned short mdate;
    unsigned short lcluster;
    unsigned int filesize;
} FatDirEntryT;

int  pflush(void);
int  pclose(void);
int  popen(char *s, char mode);
int  pread(char *ubuf, int count);
int  pgetc(void);
int  pwrite(char *ubuf, int count);
int  pputs(char *b);
int  pputc(int c);
int  seek(int pos);
int  popendir(void);
int  pchdir(char *path);
int  pmkdir(char *fname);
void pstat(FatDirEntryT *direntry);
int  mount_explicit(int DO, int CLK, int DI, int CS);
void unmount(void);
int  loadhandle(int *handle);
void loadhandle0(void);
int  nextfile(char *fbuf);
int  tell(void);
int  get_filesize(void);
char *hgets(int *handle, char *ubuf, int count);
void pchmod(int modebits);
