int Tokenize(char *str, char **tokens, int maxnum, char *tokenbuf);
int StrToBin(char *str);
int StrToQuad(char *str);
int StrToHex(char *str);
int StrToDec(char *str);
int StrCompNoCase(char *str1, char *str2);
int SearchList(char **list, char *str);
int SearchDelimiters(char *str);
int CheckForUnicode(FILE *infile);
int ReadString(char *buf, int size, FILE *infile, int unicode);
char *FindChar(char *str, int val);
char *SkipChars(char *str, char *chars);
char *FindChars(char *str, char *chars);
FILE *FileOpen(char *fname, char *mode);
void RemoveCRLF(char *buffer);
